# Generated by Django 3.1.4 on 2020-12-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airbus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4)),
                ('city', models.CharField(choices=[('DEL', 'DELHI'), ('MUB', 'MUMBAI'), ('PUN', 'PUNE'), ('BGL', 'BANGLORE'), ('CHD', 'CHANDIGARH'), ('AHD', 'AHEMDABAD')], default='DEL', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_city', models.CharField(choices=[('DEL', 'DELHI'), ('MUB', 'MUMBAI'), ('PUN', 'PUNE'), ('BGL', 'BANGLORE'), ('CHD', 'CHANDIGARH'), ('AHD', 'AHEMDABAD')], default='DEL', max_length=3)),
                ('to_city', models.CharField(choices=[('DEL', 'DELHI'), ('MUB', 'MUMBAI'), ('PUN', 'PUNE'), ('BGL', 'BANGLORE'), ('CHD', 'CHANDIGARH'), ('AHD', 'AHEMDABAD')], default='BGL', max_length=3)),
                ('airbus', models.ManyToManyField(to='airlineServiceAPI.Airbus')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=1)),
                ('job', models.CharField(choices=[('hostess', 'HOSTESS'), ('pilot', 'PILOT')], default='pilot', max_length=7)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlineServiceAPI.airlines')),
            ],
        ),
        migrations.CreateModel(
            name='AirbusSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('on', 'ON_TIME'), ('delayed', 'DELAYED'), ('early', 'BEFORE_TIME')], default='on', max_length=7)),
                ('delayed_by', models.IntegerField()),
                ('airbus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlineServiceAPI.airbus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlineServiceAPI.route')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlineServiceAPI.terminal')),
            ],
        ),
    ]
